services:
    dom_remind_bot:
        build: .
        container_name: dom_remind_bot

        # restart: on-failure:5
        environment:
            BOT_TOKEN: ${BOT_TOKEN}
            DB_URL: ${DB_URL}
            ADMIN: ${ADMIN}

            LOGGING: ${LOGGING:-ERROR}

        volumes:
            - ./app:/code/app:ro
            - ./alembic:/code/alembic

        networks:
            - main

        # command:
        #     - bash
        #     - -c
        #     - "alembic revision --autogenerate -m 'create tld_zones table'"

networks:
    main:
        external: true
