"""create account table

Revision ID: 001
Revises:
Create Date: 2023-03-20 10:03:56.034181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column('role', sa.String(), nullable=True),
        sa.Column('state', sa.String(), nullable=True),
        sa.Column('is_bot', sa.String(), nullable=True),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('language_code', sa.String(), nullable=True),
        sa.Column('is_premium', sa.String(), nullable=True),
        sa.Column('added_to_attachment_menu', sa.String(), nullable=True),
        sa.Column('can_join_groups', sa.String(), nullable=True),
        sa.Column('can_read_all_group_messages', sa.String(), nullable=True),
        sa.Column('supports_inline_queries', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
