"""create tld_zones table

Revision ID: 006
Revises: 005
Create Date: 2026-03-25 11:06:05.561316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tld_zones',
    sa.Column('tld', sa.String(), nullable=False),
    sa.Column('has_rdap', sa.Boolean(), nullable=False),
    sa.Column('rdap_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tld')
    )
    op.create_unique_constraint(None, 'domains', ['id'])
    op.create_unique_constraint(None, 'settings', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('', 'users', type_='unique')
    op.drop_constraint('', 'settings', type_='unique')
    op.drop_constraint('', 'domains', type_='unique')
    op.drop_table('tld_zones')
    # ### end Alembic commands ###
